### ISSUE TITLE
建议好好写文档

### ISSUE THREAD

**Issue by leobuzhi** [go-macaron/docs#16]
文档错误有不少，代码有些跑起来会报错，就算在源码打log也不清楚问题处在哪里了，对初学者不友好，还是希望写完文档自己测试一下吧。还是比较看好这个项目的。

**Comment by leobuzhi** [comment]
就比如会话管理那一章的demo，报了middleware render hasn't been registered 的panic。看源码是两个method。
func (r *TplRender) HTMLSet(status int, setName, tplName string, data interface{}, htmlOpt ...HTMLOptions) {
	r.renderHTML(status, setName, tplName, data, htmlOpt...)
}

func (r *DummyRender) HTMLSet(int, string, string, interface{}, ...HTMLOptions) {
	renderNotRegistered()
}

具体到了func (ctx *Context) renderHTML(status int, setName, tplName string, data ...interface{}) {    的
ctx.Render.HTMLSet(status, setName, tplName, ctx.Data) ，然后就不知道为什么会出这个问题了，对新手不友好。

**Comment by unknwon** [comment]
多谢反馈，session demo 的错误已经修复并更新。
