### ISSUE TITLE
请教一下 https://go-macaron.com/ 用的什么文档生成工具？

### ISSUE THREAD

**Issue by leopku** [go-macaron/docs#26]
谢了先。

**Comment by unknwon** [comment]
用的 https://www.gitbook.com/ 的托管服务

**Comment by leopku** [comment]
Hi @unknwon ,

Markdown 转 HTML 用的就是 gitbook 吗？

gitbook 默认生成的 html 不如 https://go-macaron.com/ 的美观。方便透露一下用的什么 theme 吗？

**Comment by unknwon** [comment]
害。。我用的就是全默认的设置，他会自动转 MD 到 HTML 的

**Comment by leopku** [comment]
> 害。。我用的就是全默认的设置，他会自动转 MD 到 HTML 的

好，我再去试试，多谢！

**Comment by leopku** [comment]
我把 go-macaron 的文档 clone 到本地，运行 `gitbook serve`，报：
```
Template render error: (/Users/leo/Project/text/go-macaron-docs/README.md) [Line 5, Column 2]
  unknown block tag: hint
```

请教下，这个 hint 是哪个插件带的吗？
装了好几个插件 `gitbook-plugin-flexible-alerts`、`gitbook-plugin-hints-istex`、`gitbook-plugin-blurbs`、`gitbook-plugin-hints`、`gitbook-plugin-flexible-alerts` 都无效，仍旧报上面这个 `unknown block tag: hint`。

请教下大佬，您的 gitbook 是安装了哪些插件吗？

**Comment by unknwon** [comment]
这不是原先的 gitbook CLI，是直接通过 gitbook.com 导入的。。。

**Comment by leopku** [comment]
> 这不是原先的 gitbook CLI，是直接通过 gitbook.com 导入的。。。

明白了，多谢大佬。
