### ISSUE TITLE
Regular Expressions

### ISSUE THREAD

**Issue by jsb01** [go-macaron/docs#7]
Hi,

I have a question regarding regular expressions in your Framework:
If I have a route like this

`m.Get("/user/:id([0-9]+)", func(ctx *macaron.Context) string {
    return fmt.Sprintf("User ID: %s", ctx.Params(":id"))
})`

and I enter a URL like http://localhost:4000/user/a12b3c, shouldn't it give me a 404? Instead it is returning "User ID: 12". Or is it intended to work this way?

**Comment by unknwon** [comment]
Expression `[0-9]+` certainly is not very restricted, which is expected you got  `12`.

`^[0-9]+$` is more restricted.

**Comment by jsb01** [comment]
Expression `^[0-9]+$` does, what I expected. 
Thank You!
